### ISSUE TITLE
Fake apple website

### ISSUE THREAD

**Issue by cizordj** [FiltersHeroes/KADhosts#17]
Hi I came across with this link on my email: (https://newsappsupportid.com/) where they say that my apple account has been blocked and they want my credit card number (phishing)
Just saying... It's still not in anybody's host file.

**Comment by azet12** [comment]
Thanks for reporting. These phishing websites usually go offline really fast, so it's hard to include them in hosts files - anti-viruses with good signatures block those. This one is not working anymore.
