### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by lmmo** [FiltersHeroes/KADhosts#31]
There are two invalid domains. I get the following error message:

```
  [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
  [✓] Status: Retrieval successful
  [i] Received 10879 domains, 2 domains invalid!
      Sample of invalid domains:
      - getin-secure-bank.xyz‎
      - www.getin-secure-bank.xyz‎`
```

**Comment by krystian3w** [comment]
Fixed:

https://github.com/PolishFiltersTeam/KAD/issues/1418

**Comment by krystian3w** [comment]
Duplicate of https://github.com/PolishFiltersTeam/KAD/issues/1418

**Comment by krystian3w** [comment]
Guilty was https://en.wikipedia.org/wiki/Left-to-right_mark

http://getin-secure-bank.xn--xyz-7t7s/

**Comment by lmmo** [comment]
Great!
