### ISSUE TITLE
Invalid domains on list

### ISSUE THREAD

**Issue by okjustin** [FiltersHeroes/KADhosts#48]
Hello,

I just wanted to bring it to your attention that PiHole has flagged the following domains from your list as invalid:

`www.|movieonlives.com`
`|movieonlives.com`

Thanks

**Comment by hawkeye116477** [comment]
It's duplicate of https://github.com/FiltersHeroes/KAD/issues/2108.

**Comment by krystian3w** [comment]
Duplicate of https://github.com/FiltersHeroes/KAD/issues/2108
