### ISSUE TITLE
kinguin.net - false blocked domain

### ISSUE THREAD

**Issue by MatanGit** [FiltersHeroes/KADhosts#49]
Hello,

Today while trying to get to **kinguin.net** I found that it was on your blocked list.
Took me some time to find that you added this domain 10 days ago on version 2022.6.19.3 ([link to the commit](https://github.com/FiltersHeroes/KADhosts/commit/64d791597d7f0beccca61ed544a3aa6d92e965f6))

I'm pretty sure this is a mistake and this domain shouldn't be blocked.
In case I'm wrong I would be happy to know if something happened with this service that I'm not aware of.

**Comment by krystian3w** [comment]
`https://forum.dobreprogramy.pl/t/czy-zakup-klucza-do-vmware-workstation-pro-prze-kinguin-net-jest-legalny/655711`

https://forum-dobreprogramy-pl.translate.goog/t/czy-zakup-klucza-do-vmware-workstation-pro-prze-kinguin-net-jest-legalny/655711?_x_tr_sl=pl&_x_tr_tl=en&_x_tr_hl=pl

**Comment by MatanGit** [comment]
As someone who used this site for over 5 years I can tell you that it does operate in the grey area. After pointing that out, I should also note that I never encountered a problem that wasn't resolved with their support in less than 24 hours. 
This is a platform for 3rd party key resellers . That gives me and other people  the opportunity to pay a reasonable price for games and other software while bypassing region/country limitation and higher prices.
Take a look at Steam and how they offer the same game with different prices for other regions  ([site that collect data on steam](https://steamdb.info/app/1286680/)).

Like I said in the start, this site is in the grey area of things, but, the site is  still supported by companies like PayPal, Kaspersky and many others. eBay for example is also a site that offers 3rd party resellers to sell things on their site, and sometime you get scammed there too.


I should also note that I'm not affiliated with this site in any way, just a simple user who found out one day that I was no longer able to connect and wanted to know why.
