### ISSUE TITLE
`anuluj-dlug.pl` | `anuluj-mandat.pl`

### ISSUE THREAD

**Issue by PatrykMis** [FiltersHeroes/KADhosts#50]
Problem już wyjaśniałem [tutaj](https://github.com/FiltersHeroes/KAD/issues/2131).

**Comment by hawkeye116477** [comment]
Ta lista hosts jest robiona automatycznie z listy KAD, więc nie potrzeba duplikować zgłoszeń :smile:.

**Comment by krystian3w** [comment]
Duplicate of https://github.com/FiltersHeroes/KAD/issues/2131
