### ISSUE TITLE
sites.google.com - exclude path as compatible

### ISSUE THREAD

**Issue by kenrick95** [FiltersHeroes/KADhosts#54]
The following entries are included in `KADhosts.txt`

```
0.0.0.0 sites.google.com/view/da2-globaltradruv-com
0.0.0.0 www.sites.google.com/view/da2-globaltradruv-com
```

These are not valid hostnames, and it causes issue in https://github.com/StevenBlack/hosts/issues/2150

**Comment by krystian3w** [comment]
As workaround we can in based file add `,important`, change `$all` to `$doc` or asterisk.
