### ISSUE TITLE
Gootloader malware command and control servers

### ISSUE THREAD

**Issue by realugbun** [FiltersHeroes/KADhosts#56]
Goot loader infects machines and is the first step in a ransomware attack.

A full writeup on goot loader listing the servers can be found here.

https://www.mandiant.com/resources/blog/tracking-evolution-gootloader-operations

```
## Goot loader command and control
0.0.0.0 jonathanbartz.com
0.0.0.0 jp.imonitorsoft.com
0.0.0.0 junk-bros.com
0.0.0.0 kakiosk.adsparkdev.com
0.0.0.0 kepw.org
0.0.0.0 kristinee.com
0.0.0.0 lakeside-fishandchips.com
```

**Comment by krystian3w** [comment]
IP can not by used in HOSTS or domains list: https://github.com/StevenBlack/hosts/issues/1006 https://github.com/StevenBlack/hosts/issues/1004

**Comment by realugbun** [comment]
I have updated the request to remove pure ip addresses.

**Comment by realugbun** [comment]
Thank you for adding these and thank you for maintaining the list!

**Comment by realugbun** [comment]
Looks like the j in `junk-bros.com` was missed.
https://github.com/FiltersHeroes/KADhosts/commit/c4540fd9a1b54f1327251f47005466f7edb3a30a

**Comment by krystian3w** [comment]
Addressed in https://github.com/FiltersHeroes/KADhosts/commit/59067d33672dcb1642fe6d46b3c45e0c771ab353 + https://github.com/FiltersHeroes/KADhosts/commit/d09acf0243ce29ccab11187ccab593843551ca6c.
