### ISSUE TITLE
sslip.io

### ISSUE THREAD

**Issue by WFANG12719** [FiltersHeroes/KADhosts#67]
### Bloker (Blocker)

uBlock origin

### Link bezpośredni, na którym występuje problem

```markdown
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

Line 141515

.sslip.io -> Is this line typo or part of the last line?
```

### Opis błędu

Error Line # 141515

.sslip.io -> Is this line typo or part of the last line?

### Dodatkowe informacje mogące mieć znaczenie

either this line is typo or part of the last line . Or it is just comment but missing #

**Comment by krystian3w** [comment]
For uBo better use that list:

[https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt&title=KAD%20-%20Przekr%C4%99ty "https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt&title=KAD%20-%20Przekr%C4%99ty").

Fallback page with subscribtion/mirrors:

[https://majkiit.github.io/polish-ads-filter/#kad_-_przekr%c4%99ty](https://majkiit.github.io/polish-ads-filter/#kad_-_przekr%c4%99ty "https://majkiit.github.io/polish-ads-filter/#kad_-_przekr%c4%99ty")
