### ISSUE TITLE
Question about high amount of sleepers/parked domains

### ISSUE THREAD

**Issue by ldlac** [FiltersHeroes/KADhosts#79]
Hi, first of all, thanks for your good work, you guys have a huge hosts list! 

I was wondering why there is so many sleepers/parked domains in the list? I'm actively building an hosts list using multiple sources and I found out that you guys have around `31833` sleepers. Are you keeping them just in case they submerged? Is it safe to remove them?

**Comment by hawkeye116477** [comment]
We're removing parked domains if our script will find them.  How you found so many?

**Comment by krystian3w** [comment]
There may also be a problem that a given domain has a deliberately damaged homepage and only with unknown parameters or URI path it returns text worth blocking.

We certainly do not know such parameters and paths for CERT POLSKA (they may not necessarily be willing to publish the exact URLs from the reports).

**Comment by ldlac** [comment]
Thanks for your responses

I'm currently experimenting with https://pypi.org/project/dnspython/ simply trying to resolve the domain. So they simply do not have an A record which is why they are still on the list, my bad on this just figured that out.
I recently discovered this tool too https://pypi.org/project/PyFunceble/ which could give me better results.

**Comment by hawkeye116477** [comment]
We're also using dnspython for our script, but that's just one of the methods => https://github.com/FiltersHeroes/ScriptsPlayground/blob/master/scripts/ECODFF.py.
