### ISSUE TITLE
0.0.0.0 www.||immediate-bitwave.com

### ISSUE THREAD

**Issue by StevenBlack** [FiltersHeroes/KADhosts#81]
Hello everyone!

I want to draw your attention to this issue...

https://github.com/StevenBlack/hosts/issues/2771

... is `0.0.0.0 ||immediate-bitwave.com` and `0.0.0.0 www.||immediate-bitwave.com` a listing mistake here?

Cheers!

**Comment by StevenBlack** [comment]
@hawkeye116477 without discussion, I can't tell if you've handled the incorrect `www.||immediate-bitwave.com` as well?

Just checking 😄

**Comment by krystian3w** [comment]
Probably too quick find and replace in Notepad++: https://github.com/FiltersHeroes/KAD/commit/f3303f8a0b1136976cb5f737fdcda627fb50f8fe#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R4

**Comment by hawkeye116477** [comment]
> if you've handled the incorrect www.||immediate-bitwave.com as well?

Yeah, I'm fast :smile:. Well, www version is generated by script, so it's not needed to fix that by manual.
