### ISSUE TITLE
Invalid domain `www.`

### ISSUE THREAD

**Issue by StevenBlack** [FiltersHeroes/KADhosts#84]
In the file https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt we see an invalid domain `.www`.

Here's the surrounding region.

```
0.0.0.0 www.777infosygnal.kookingclub.com
0.0.0.0 www.0901d.openfinparticls.cfd
0.0.0.0 www.
0.0.0.0 www.a-tocard-pl.treasure-shop.org
0.0.0.0 www.a.ero.bullrun-new.com
0.0.0.0 www.ac.bkaliorsa.com
```

**Comment by hawkeye116477** [comment]
Yeah, looks like here's culprit => https://github.com/FiltersHeroes/KADhosts/commit/959aaaf2b78dc59cb8d4c0c2c7fe4ad97aba9fd8#diff-eb91ad6cdbf975802579d580b5dbcee6e8845116b123200d8af480417b91332dR424.
